# Generated by Django 3.0.8 on 2020-09-21 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_passsave_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passsave',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passsave', to=settings.AUTH_USER_MODEL),
        ),
    ]
